export const GET_MISTAKE_FOLLOWID_REQUEST = "GET_MISTAKE_FOLLOWID_REQUEST";
export const GET_MISTAKE_FOLLOWID_SUCCESS = "GET_MISTAKE_FOLLOWID_SUCCESS";
export const CREATE_MISTAKE_REQUEST = "CREATE_MISTAKE_REQUEST";
export const CREATE_MISTAKE_SUCCESS = "CREATE_MISTAKE_SUCCESS";
export const DELETE_MISTAKE_REQUEST = "DELETE_MISTAKE_REQUEST";
export const EDIT_MISTAKE_REQUEST = "EDIT_MISTAKE_REQUEST";

export const GET_MISTAKE_BY_ADMIN_REQUEST = "GET_MISTAKE_BY_ADMIN_REQUEST";
export const GET_MISTAKE_BY_ADMIN_SUCCESS = "GET_MISTAKE_BY_ADMIN_SUCCESS";
