export const CREATE_DAILY_REPORT_REQUEST = "CREATE_DAILY_REPORT_REQUEST";
export const GET_DAILY_REPORT_REQUEST = "GET_DAILY_REPORT_REQUEST";
export const GET_DAILY_REPORT_SUCCESS = "GET_DAILY_REPORT_SUCCESS";
export const GET_DAILY_REPORT_BY_DATE_REQUEST =
  "GET_DAILY_REPORT_BY_DATE_REQUEST";
export const DELETE_DAILY_REPORT_REQUEST = "DELETE_DAILY_REPORT_REQUEST";

export const GET_DAILY_REPORT_BY_ADMIN_REQUEST =
  "GET_DAILY_REPORT_BY_ADMIN_REQUEST";
export const GET_DAILY_REPORT_BY_ADMIN_SUCCESS =
  "GET_DAILY_REPORT_BY_ADMIN_SUCCESS";
export const DELETE_REPORT_BY_ADMIN_REQUEST = "DELETE_REPORT_BY_ADMIN_REQUEST";
export const GET_DAILY_REPORT_ADMIN_BY_DATE_REQUEST =
  "GET_DAILY_REPORT_ADMIN_BY_DATE_REQUEST";
export const GET_DAILY_REPORT_ADMIN_BY_DATE_SUCCESS =
  "GET_DAILY_REPORT_ADMIN_BY_DATE_SUCCESS";
