export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const ADD_ROLE_REQUEST ="ADD_ROLE_REQUEST";
export const ADD_ROLE_SUCCESS ="ADD_ROLE_SUCCESS";
export const DELETE_ROLE_REQUEST ="DELETE_ROLE_REQUEST";
